16) Дана система линейных алгебраических уравнений с четырьмя неизвестными.
1. Преобразовать систему к виду, пригодному для приминения принципа сжимающих операторов
2. Методом простых итераций найти приближенные решения с точностью $10^{-2}$ и с точностью $10^{-4}$, используя априорную и апостериорную оценки числа итераций.
3. Найти точное решение системы и сравнить с приближенным.

$$
\begin{cases}
           2x_1 + x_2 + 2x_3 + 3x_4 = 8\\
           3x_1 + 3x_3 = 6\\
           2x_1 - x_2 + 3x_4 = 4\\
           x_1 + 2x_2 - x_3 + 2x_4 = 4
\end{cases}
$$

### Вычисления

In [11]:
import numpy as np
import math as mat
import matplotlib.pyplot as plt

a = np.array([[2, 1, 2, 3],
             [3, 0, 3, 0],
             [2, -1, 0, 3],
             [1, 2, -1, 2]])

b = np.array([8,6,4,4])

print('Матрица A\n', a, '\n')
print("Определитель матрицы =", np.linalg.det(a), '\n')

at = a.T
print('Матрица A транспонированная\n', at, '\n')

ata = a.T.dot(a)
print('ATA\n',ata, '\n')

#первый массив - собс. числа, второй массив - собс. векторы
l_ata = np.linalg.eig(ata)
print('Собственные числа ATA\n',l_ata)

c = np.eye(4) - ata / l_ata[0][0]
print('\nМатрица С =\n',c)

d = at.dot(b) / l_ata[0][0]
print('\nМатрица d =\n', d)

l_c = np.linalg.eig(c)
print('\nСобственные числа матрицы C\n',l_c)

alfa = l_c[0][2]
print('\nКоэффициент сжатия a =', alfa, '\n')

Матрица A
 [[ 2  1  2  3]
 [ 3  0  3  0]
 [ 2 -1  0  3]
 [ 1  2 -1  2]] 

Определитель матрицы = -59.999999999999986 

Матрица A транспонированная
 [[ 2  3  2  1]
 [ 1  0 -1  2]
 [ 2  3  0 -1]
 [ 3  0  3  2]] 

ATA
 [[18  2 12 14]
 [ 2  6  0  4]
 [12  0 14  4]
 [14  4  4 22]] 

Собственные числа ATA
 (array([39.54966651, 14.19628478,  1.29224714,  4.96180157]), array([[ 0.64824057,  0.22045953,  0.72803426,  0.03388032],
       [ 0.11438303, -0.25212811,  0.0192103 , -0.96071791],
       [ 0.40391597,  0.7034755 , -0.56578888, -0.14784131],
       [ 0.63525788, -0.62685822, -0.38662647,  0.23241379]]))

Матрица С =
 [[ 0.54487606 -0.05056933 -0.30341596 -0.35398529]
 [-0.05056933  0.84829202  0.         -0.10113865]
 [-0.30341596  0.          0.64601471 -0.10113865]
 [-0.35398529 -0.10113865 -0.10113865  0.44373741]]

Матрица d =
 [1.16309451 0.30341596 0.7585399  1.11252518]

Собственные числа матрицы C
 (array([-1.11022302e-15,  6.41051720e-01,  9.67325966e-01,  8.74542518e-01]), arr

In [12]:
import numpy as np
import math as mat
import matplotlib.pyplot as plt

e1 = 10**(-2)
e2 = 10**(-4)

x0 = np.array([0,0,0,0])
print('x0 = ',x0)

x1 = c.dot(x0) + d
print('x1 = ', x1)

#расстояние
p = np.sqrt(np.sum((x0 - x1)**2))
print('p = ', p)

#априорная оценка числа итераций
napr_e1 = np.around(np.log((e1*(1-alfa))/p)/(np.log(alfa))) + 1 #log_a(value)
print('napr_e1 = ', napr_e1)

napr_e2 = np.around(np.log((e2*(1-alfa))/p)/(np.log(alfa))) + 1 #log_a(value)
print('napr_e2 = ', napr_e2)

xn_1 = x0
xn = [0,0,0,0]

#коэф. для условия
comparable = alfa/(1-alfa)

e = [e1,e2]

#решение слау
x = np.linalg.solve(a,b)
print('Точное решение СЛАУ =', x)

#апостериорная оценка
count = 0
print('Итерационные решения:')
for i in e:
    while True:
        count += 1
        xn = c.dot(xn_1) + d
        if ((comparable * np.sqrt(np.sum((xn - xn_1)**2))) <= i):
            print('x_',count,' = ',xn)
            print('P2(x_',count,', x) = ', np.sqrt(np.sum((xn - x)**2)))
            break
        xn_1 = xn

print()

x0 =  [0 0 0 0]
x1 =  [1.16309451 0.30341596 0.7585399  1.11252518]
p =  1.8049778794631721
napr_e1 =  260.0
napr_e2 =  399.0
Точное решение СЛАУ = [1. 1. 1. 1.]
Итерационные решения:
x_ 91  =  [1.00726783 1.00018769 0.99435132 0.99614144]
P2(x_ 91 , x) =  0.00998261979295268
x_ 231  =  [1.00007178 1.00000189 0.99994421 0.99996188]
P2(x_ 231 , x) =  9.859844369884235e-05



In [13]:
#проверка априорной оценки
xn_1 = [0,0,0,0]
xn = [0,0,0,0]

for i in range(1, 260):
    xn = c.dot(xn_1) + d
    xn_1 = xn
print('xn = ', xn)

xn =  [1.00002739 1.00000072 0.99997871 0.99998545]
